# Generated by Django 5.2.4 on 2025-10-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
